@startuml
allowmixing

node "Backend" #LightBlue {
rectangle Express [
<b>Express</b>
====
Routes
Controllers
Models
]
rectangle NodeJS [
<b>Node.js</b>
====
JavaScript runtime
Runs transpiled TypeScript
]
rectangle Mongoose [
<b>Mongoose</b>
====
Object document mapping tool
]
}

node "Frontend" #OrangeRed{
rectangle Svelte [
<b>Svelte</b>
====
Pages
Components
]

rectangle Tailwind [
<b>Tailwind</b>
====
CSS
]
}

database "Database" #LightGreen {
rectangle MongoDB [
<b>MongoDB</b>
====
NoSQL database
]
}

node "Infrastructure" #DarkGray{
rectangle env [
<b>.env</b>
====
Environment variables
]
rectangle Docker [
<b>Docker</b>
====
Containerizes application
]
rectangle Tailscale [
<b>Tailscale</b>
====
Remote self hosted server access
]
rectangle Launcher [
<b>Launcher</b>
====
Some python code
]
}

package "Build Tools" #Yellow {
rectangle ESLint [
<b>ESLint</b>
====
Linting
]
rectangle Vite [
<b>Vite</b>
====
Testing tool
Module bundler
]
}

actor User

Express <--> Mongoose : Talks to
Mongoose <--> Database: Talks to
Frontend <--> Express: Talks to
Docker --> Backend : Containerizes
Docker --> Database : Containerizes
Docker --> Tailscale : Containerizes
User --> Frontend : Views
Tailscale <--> Express : Remotely accesses
Launcher --> Docker : Launches
User --> Launcher : Uses
Express --> NodeJS : Runs on
Tailwind --> Svelte : Stylizes
Vite --> Svelte : Bundles

@enduml