#version: '3'
name: assetatlas-project

services:
  assetatlas:
    image: assetatlas
    volumes:
      - ./.env:/usr/src/app/docker/.env
      - rollup-cache:/usr/src/app/.rollup-cache
      - rollup-module-cache:/usr/src/app/node_modules/.cache/rollup
      - tsbuild-cache:/usr/src/app/.tsbuildcache
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "1"
      cache_from:
        - assetatlas:latest
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/assetatlas_db
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - default

networks:
  default:
    driver: bridge
    name: assetatlas-bridge

volumes:
  mongo-data:
  rollup-cache:
    name: assetatlas-rollup-cache
  rollup-module-cache:
    name: assetatlas-rollup-module-cache
  tsbuild-cache:
    name: assetatlas-tsbuild-cache
