version: '3.4'

services:
  assetatlas:
    image: assetatlas
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/assetatlas_db
    ports:
      - 3000:3000

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
