FROM node:20-bullseye

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY tsconfig.json vite.config.ts tailwind.config.ts rollup.config.js ./

EXPOSE 3000

CMD ["npm", "run", "dev"]