services:
  assetatlas:
    image: assetatlas
    volumes:
      - ./.env:/usr/src/app/docker/.env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/assetatlas_db
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
